### ISSUE TITLE
Open Select filter using Typescript/Javascript?

### ISSUE THREAD

**Issue by relvis** [moayadnajd/nativescript-filter-select#22]
Hi there, this is a very useful plugin and I am considering using. However, I would like to customize some behavior for example, is there any way to open the widget using TypeScript/Javascript? Something like:

`(<FilterSelect>this.selectLocation.nativeElement).open()` ?

Thanks!

**Comment by moayadnajd** [comment]
@relvis it will  be nice idea i will make  this soon

**Comment by VChabrette** [comment]
@relvis @moayadnajd Just to say, I'm totally craving this addition ; in fact, because time is a real issue for me right now, I had to act fast and implemented a workaround myself by notifying the SelectButton of a programmatically sent tap (inside of a custom Angular directive in my case)
`(<FilterSelect>this.element).addEventListener('tap', () => selectButton.notify({ eventName: 'tap', object: selectButton }));`

**Comment by moayadnajd** [comment]
@VChabrette and @relvis  please use open() method please see demo folder

**Comment by VChabrette** [comment]
@moayadnajd It's working perfectly ! However, it seems like you forgot to remove the `console.log('->>>>>>>>>>this.modalPage.on("loaded", function(args)');` haha
